---
driver:
  name: vagrant
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
  - name: centos-7.1

suites:
  - name: default 
    driver:
      network:
        - ["private_network", {ip: "192.168.17.100"}]
    run_list:
      - recipe[apt::default]
      - recipe[deploy-django::default]
    attributes:
